name: Translations

on: [push]

jobs:
  check-translations:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2

      - name: Install dev dependencies
        run: npm install --only=dev

      - name: Check all text has been translated
        run: npm run check-translations
